download:
	#wget https://raw.githubusercontent.com/alexlitel/congresstweets-automator/master/data/historical-users-filtered.json -O historical-users-filtered.json-tmp
	wget https://theunitedstates.io/congress-legislators/legislators-current.csv -O legislators-current.csv-tmp
	wget https://theunitedstates.io/congress-legislators/legislators-historical.csv -O legislators-historical.csv-tmp
